version: "3.3"

services:
  db:
    image: mongo
    networks:
      default:
        ipv4_address: 172.16.1.1
    environment:
      - MONGO_INITDB_DATABASE=admin
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./db:/data/db

  strapi:
    image: strapi/strapi:3.5.2
    networks:
      default:
        ipv4_address: 172.16.1.2
    environment:
      - APP_NAME=cms
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_NAME=${CMS_DB_NAME}
      - DATABASE_PORT=${DB_PORT}
      - DATABASE_SSL=false
      - HOST=${CMS_HOST}
      - ADMIN_USERNAME=${CMS_ADMIN_USERNAME}
      - ADMIN_EMAIL=${CMS_ADMIN_EMAIL}
      - ADMIN_PASSWORD=${CMS_ADMIN_PASSWORD}
    ports:
      - 1337:1337
    volumes:
      - type: bind
        source: ./cms
        target: /srv/app
    depends_on:
      - db

  server:
    build: ./server
    networks:
      default:
        ipv4_address: 172.16.1.3
    environment:
      - SERVER_PORT=34543
      - CMS_HOST=${CMS_HOST}
      - CMS_EMAIL=${CMS_ADMIN_EMAIL}
      - CMS_PASSWORD=${CMS_ADMIN_PASSWORD}
      - CMS_PORT=${CMS_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    restart: on-failure
    volumes:
      - ./config.json:/home/node/config.json
    depends_on:
      - db
      - strapi
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16
          gateway: 172.16.0.1
    driver_opts:
      com.docker.network.bridge.name: "docker1"
